// Generated by CoffeeScript 1.10.0
(function() {
  var dialog, remote;

  remote = require('remote');

  dialog = remote.require('dialog');

  document.getElementById("btn").onclick = function() {
    console.log("dialog");
    return dialog.showOpenDialog(function(filename) {
      return console.log(filename);
    });
  };

  console.log("read");

}).call(this);
