// Generated by CoffeeScript 1.10.0
(function() {
  var dialog, filepath, fs, options, remote;

  remote = require('remote');

  dialog = remote.require('dialog');

  fs = require('fs');

  filepath = "null";

  options = {
    filters: [
      {
        name: 'csv',
        extensions: ['csv']
      }
    ]
  };

  document.getElementById("btn").onclick = function() {
    console.log("dialog");
    return dialog.showOpenDialog(options, function(filepath) {
      var stat;
      console.log("file path:" + filepath);
      stat = fs.statSync("" + filepath);
      console.log("stat:%O", stat);
      if (stat.isFile() === true) {
        console.log("true");
        return fs.readFile("" + filepath, 'utf8', function(err, data) {
          if (err) {
            throw err;
          }
          return console.log(data);
        });
      } else {
        return alert("Not a file!");
      }
    });
  };

}).call(this);
